module.exports = `
  # a price entity consist of amount and currency
  type Price {
    amount: Int!
    currency: String!
  }

  # an image entity
  type Image {
    # id: Int!
    fullUrl: String!
    width: Int
    height: Int
  }

  # a product entity
  type Product {
    id: ID!
    title: String
    slug: String!
    descriptionMarkdown: String
    quantity: Int
    price: Price
    category: String
    images: [Image]
  }

  # a product list
  type ProductList {
    amount: Int! @default(value: 5)
    offset: Int!
    total: Int
    remaining: Int
    items: [Product]
  }

  # a catalogue contains products
  type Catalogue {
    id: ID!
    product: ProductList
    title: String!
    metaTitle: String
  }

  # query for types
  type Query {
    # Return a catalogue contains list of product
    catalogue(amount: Int, offset: Int): Catalogue!

    # Return a product by its id
    product(id: ID): Product!

    # Hello World!
    hello(name: String): String!
  }
`;
